"""Initial Migration

Revision ID: 7309005a278d
Revises: 0b2e6c666fa9
Create Date: 2018-06-29 17:25:04.655318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7309005a278d'
down_revision = '0b2e6c666fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('down_vote', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('up_vote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'up_vote')
    op.drop_column('pitches', 'down_vote')
    # ### end Alembic commands ###
